kmlv/otree_express

- mauss_questionnaire/_builtin/__init__.py
- mauss_questionnaire/models.py
- mauss_questionnaire/templates/mauss_questionnaire/MyPage.html
- mauss_questionnaire/templates/mauss_questionnaire/Results.html
- mauss_questionnaire/tests.py
- mauss_questionnaire/views.py
third party wait page error [solved]
> third party wait page error [solved]

- settings.py
> amt_settings_aws

- settings.py
I'm modifying the participation fee becuse it generates too high payments in real money
> participation fee modifications

- settings.py
participation fee and real money per point
> participation fee and real money per point

- settings of qualifications in mturk [short_guide].md
> qualifications guide

- settings of qualifications in mturk [short_guide].md
settings of qualifications in mturk [short_guide]
> settings of qualifications in mturk [short_guide]

- PTT_expression/templates/PTT_expression/ADecides.html
- PTT_expression/templates/PTT_expression/AllBdmCont.html
- PTT_expression/templates/PTT_expression/BPredicts.html
- PTT_expression/templates/PTT_expression/Results.html
- PTT_expression/views.py
- settings.py
> currency_points config

- PANAS_final/_builtin/__init__.py
- PANAS_final/models.py
- PANAS_final/templates/PANAS_final/DoneQuestionnaire.html
- PANAS_final/templates/PANAS_final/QuestionnairePage1.html
- PANAS_final/templates/PANAS_final/QuestionnairePage2.html
- PANAS_final/templatetags/index.py
- PANAS_final/tests.py
- PANAS_final/views.py
- PTT_express_instructions/views.py
- PTT_expression/templates/PTT_expression/AllBdmCont.html
- PTT_expression/templates/PTT_expression/AllBdmList.html
- PTT_expression/templates/PTT_expression/Results.html
- PTT_expression/templates/PTT_expression/RolesIncome.html
- settings.py
nuevas actualizaciones (Doble PANA quest)
> nuevas actualizaciones (Doble PANA quest)

- PANAS/views.py
- PANAS_final/views.py
- PTT_express_instructions/views.py
- PTT_expression/views.py
- search_task/views.py
- settings.py
> timeouts and mturk onf

- settings.py
> changes in qualif key

- settings.py
> no qualifications

- settings.py
i created a ney aws_access key for keconlab
> qualifications again and new AWS

- PTT_expression/templates/PTT_expression/DisplayMessageToA.html
> Checking apps

- .idea/misc.xml
- .idea/oTree.iml
- PTT_expression/models.py
- PTT_expression/templates/PTT_expression/RolesIncome.html
- PTT_expression/views.py
- settings.py
deactivate timeouts 
add a waiting after initial page that generates task income
change the calculation of b_task_income in initial page
> fix issue with floats

- PTT_express_instructions/templates/PTT_express_instructions/SummaryInstructions.html
- PTT_expression/templates/PTT_expression/ADecides.html
Expand and hide the instructions.
> Expand instructions

- emo_quest_panas_mauss/templates/emo_quest_panas_mauss/QuestionnairePage1.html
- emo_quest_panas_mauss/templates/emo_quest_panas_mauss/QuestionnairePage2.html
- emo_quest_panas_mauss_2/templates/emo_quest_panas_mauss_2/QuestionnairePage1.html
- emo_quest_panas_mauss_2/templates/emo_quest_panas_mauss_2/QuestionnairePage2.html
Here's the fix for the prod server form issue. Just change the hidden to type a style.
> Fix input styling for sliders to work on production

- date-example.py
Add an example in the base directory showing how to convert between formats
> Add date examples

- PTT_expression/templates/PTT_expression/AllBdmList.html
- PTT_expression/templates/PTT_expression/advance.html
- PTT_expression/templates/PTT_expression/submit.html
Advance without any forms filled and advance with forms filled (given an option model field).
> Next button refactor

- PTT_expression/templates/PTT_expression/ElicitBdmCont.html
- PTT_expression/templates/PTT_expression/ElicitBdmList.html
Every relevant page has the buttom of instructions, except:
DisplayMessagesToR, DisplayMessagesToA, InititalStage2, and Results.
> Checking instruction 112316

- PTT_express_instructions/models.py
- PTT_express_instructions/views.py
Fields are saved in a separate error column on validation. 
#65
> Save fields on first validation

- .idea/misc.xml
- .idea/oTree.iml
- quiz_eyes/models.py
- quiz_eyes/templates/quiz_eyes/Question.html
- quiz_eyes/templates/quiz_eyes/Results.html
- quiz_eyes/templates/quiz_eyes/eyes_instructions.html
- quiz_eyes/views.py
score and timestamp in eye quiz
> score and timestamp in eye quiz

- quiz_eyes/readme_quizeyes.md
- transcrip_task/readme_transcriptiontask.md
> Readme docs

- _templates/global/Base.html
- emo_quest_panas_mauss_discrete/templates/emo_quest_panas_mauss_discrete/EmoQuestPage1.html
- emo_quest_panas_mauss_discrete/templates/emo_quest_panas_mauss_discrete/EmoQuestPage2.html
- emo_quest_panas_mauss_discrete2/templates/emo_quest_panas_mauss_discrete2/EmoQuestPage1.html
- emo_quest_panas_mauss_discrete2/templates/emo_quest_panas_mauss_discrete2/EmoQuestPage2.html
Add randomization script for questionnaire questions.
Factor arrive time to base.html
#83
> Implement randomization script

- _static/global/randomize.js
- _templates/global/Base.html
- emo_quest_panas_mauss_discrete/templates/emo_quest_panas_mauss_discrete/EmoQuestPage1.html
- emo_quest_panas_mauss_discrete/templates/emo_quest_panas_mauss_discrete/EmoQuestPage2.html
- emo_quest_panas_mauss_discrete2/templates/emo_quest_panas_mauss_discrete2/EmoQuestPage1.html
- emo_quest_panas_mauss_discrete2/templates/emo_quest_panas_mauss_discrete2/EmoQuestPage2.html
> Randomize update

- _templates/global/Base.html
In order to change the font size for the entire app, change the style in _templates/global/Base.html
> Update global font size
